# Generated by Django 3.2.5 on 2022-01-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_field', models.EmailField(max_length=254)),
                ('date_field', models.DateTimeField(auto_now_add=True)),
                ('state_field', models.BooleanField(default=False)),
            ],
        ),
    ]
