# Generated by Django 3.2.5 on 2022-01-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='state_field',
            field=models.BooleanField(),
        ),
    ]
